# Generated by Django 5.0.2 on 2024-02-29 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyHistory',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card.card')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'История',
            },
            bases=('card.card',),
        ),
    ]
