# Generated by Django 5.0.2 on 2024-03-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_myhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myhistory',
            options={},
        ),
        migrations.AddField(
            model_name='myhistory',
            name='img_2',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Второе фото'),
        ),
    ]
