# Generated by Django 5.0.2 on 2024-03-19 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_myhistory_options_card_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoneRelax',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card.card')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Второе фото')),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Третье фото')),
            ],
            options={
                'verbose_name': 'Зона отдыха',
                'verbose_name_plural': 'Зоны отдыха',
            },
            bases=('card.card',),
        ),
    ]
