# Generated by Django 5.0.6 on 2024-10-16 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_zonerelax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proiz',
            fields=[
                ('card_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='card.card')),
            ],
            options={
                'verbose_name': 'Наши производители',
            },
            bases=('card.card',),
        ),
    ]
