# Generated by Django 5.0.6 on 2025-02-03 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12, verbose_name='Имя')),
                ('number', models.CharField(max_length=15, verbose_name='Номер')),
                ('date', models.DateTimeField(default=datetime.datetime(2025, 2, 3, 8, 42, 41, 256582, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
