# Generated by Django 5.0.6 on 2025-02-03 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 9, 53, 50, 851022, tzinfo=datetime.timezone.utc)),
        ),
    ]
